### ISSUE TITLE
preact

### ISSUE THREAD

**Issue by enricostano** [andresgutgon/planb#1]
Since you're dissecting all the things, does it make any sense to try out https://github.com/developit/preact too?

Would this help even further on splitting bundles etc?

**Comment by andresgutgon** [comment]
> Would this help even further on splitting bundles etc?

How it's related splitting and switching from react to preact

> does it make any sense to try out 

I'm doing a lot of experimentation on this repo. But the goal is to have at the end a product easy to iterate with. My main concern with switching to Preact is packages ecosystem. Some packages will be compatible with Preact, other don't. I don't want to fight that

**Comment by enricostano** [comment]
> How it's related splitting and switching from react to preact

From my (little) understanding preact is splitted in atomic libraries, maybe in a part of the application you need just 5 preact libs, while in another part you need 25 of them. But maybe I'm wrong.

> My main concern with switching to Preact is packages ecosystem

Yeah, that's a good point. Although if preact garantee 100% API compatibility with react... if that's true we "shouldn't" have any compatibility problem. But again I'm no preact expert.

Another selling point of preact is that the license doesn't contain that Facebook bullshit that limits react license.

**Comment by andresgutgon** [comment]
> From my (little) understanding preact is splitted in atomic libraries

That's cool. But webpack tree shaking remove all not used code branches. Or it should. Anyway should not be our main concern. If you do an app you're fully using the view layer. So you need that code


> Another selling point of preact is that the license doesn't contain that Facebook bullshit that limits react license.

If we face that problem means we're doing something really well ;)

**Comment by enricostano** [comment]
Ok, let's close this then. Thanks!
